### ISSUE TITLE
TypeError: can't convert String into Integer

### ISSUE THREAD

**Issue by dgilperez** [devwout/activerecord_merge#2]
Hi!

Thanks for sharing, this is such a great tool to have!

I'm experiencing a `TypeError: can't convert String into Integer` when trying the lib. I'm on Rails 3.2.12. The error happens here:

```
from app/config/initializers/merge.rb:68:in `[]'    from app/config/initializers/merge.rb:68:in `block in merge_attributes!'    from app/config/initializers/merge.rb:66:in `reject!'   from app/config/initializers/merge.rb:66:in `merge_attributes!'     from app/config/initializers/merge.rb:35:in `block in merge!'
```

Any ideas? 

Many thanks !!!!

**Comment by devwout** [comment]
Hi

Maybe you are passing an array of objects to the merge! method instead of using separate arguments?

It should be

``` ruby
merge!(object1, object2)
```

Maybe you are doing

``` ruby
merge!([object1, object2])
```

**Comment by dgilperez** [comment]
Thanks! 

Yes, that's it in deed :) 

My use case is that I'm fetching a collection from the DB, using the first one as the master and the rest as the duplicates. So yes, I have an array of objects. This may be a silly question, but is there any way of converting such an array into the list of arguments the method takes? Or shall I iterate `merge!(object)` over the whole array?

Thanks a lot!!!

**Comment by devwout** [comment]
Hi

Glad we found what caused your issue ;-). You could try 

``` ruby
object.merge!(*objects)
```

The start causes the array that follows (objects) to be converted into a list of arguments.

**Comment by dgilperez** [comment]
Thanks!!! You learn something new everyday :)
