### ISSUE TITLE
Rails 4

### ISSUE THREAD

**Issue by dgilperez** [devwout/activerecord_merge#3]
Hi!

Is this code Rails4 compatible? Are you using it in production? 

Thanks for sharing!

**Comment by devwout** [comment]
The code is still used in production, on a rails 2.3.8 system. Somebody sent a [patch](https://github.com/devwout/activerecord_merge/pull/1) to make it compatible rails 3.2. It would be nice if you could try it out on rails 4. I can help you with adjustments if necessary.

**Comment by dgilperez** [comment]
Thanks for the fast response! 

I've been using it in Rails 3.2 projects without hassle, but now I'm seeing issues with a Rails 4.1 project. 

The particular error involves HBTM association. I'm getting this error:

`ActiveModel::MissingAttributeError: can't write unknown attribute `service_id'`, being `service_id` the correct field in the table / association.

I'm not sure this is related to Rails 4 or there is any error in my code, though everything else seems to be working fine.

**Comment by dgilperez** [comment]
Coming back just to confirm that the error was a bug of my code. I'm using the code with a Rails 4 project now without a hassle. Good!
