### ISSUE TITLE
How to include?

### ISSUE THREAD

**Issue by frecklebit** [devwout/activerecord_merge#4]
How do I include this in my rails app? I put it in my lib/helpers which is autoloaded but I am getting `undefined method 'merge!' for #<Provider:0x0000011459eb28>`.

**Comment by devwout** [comment]
It needs to be required. You can either put the `merge.rb` file in `config/intitializers/` or put it in `lib` and create a new file in `config/intitializers/` with `require 'lib/merge'`.

I am still using this code in a project but never bothered to package it in a gem. Sorry about that.
